// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopPhone.Main;

namespace ShopPhone.Migrations
{
    [DbContext(typeof(DBContent))]
    [Migration("20200206101313_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShopPhone.Main.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoryDescription");

                    b.Property<string>("categoryName");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("ShopPhone.Main.Models.Motherboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MotherboardCategoryId");

                    b.Property<string>("description");

                    b.Property<string>("img");

                    b.Property<string>("name");

                    b.Property<long>("price");

                    b.HasKey("Id");

                    b.HasIndex("MotherboardCategoryId");

                    b.ToTable("Motherboards");
                });

            modelBuilder.Entity("ShopPhone.Main.Models.MotherboardCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoryDescription");

                    b.Property<string>("categoryName");

                    b.HasKey("Id");

                    b.ToTable("MotherboardCategories");
                });

            modelBuilder.Entity("ShopPhone.Main.Models.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId");

                    b.Property<string>("description");

                    b.Property<string>("img");

                    b.Property<string>("name");

                    b.Property<long>("price");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Phone");
                });

            modelBuilder.Entity("ShopPhone.Main.Models.Procesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProcesorCategoryId");

                    b.Property<string>("description");

                    b.Property<string>("img");

                    b.Property<string>("name");

                    b.Property<long>("price");

                    b.HasKey("Id");

                    b.HasIndex("ProcesorCategoryId");

                    b.ToTable("Procesors");
                });

            modelBuilder.Entity("ShopPhone.Main.Models.ProcesorCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoryDescription");

                    b.Property<string>("categoryName");

                    b.HasKey("Id");

                    b.ToTable("ProcesorCategories");
                });

            modelBuilder.Entity("ShopPhone.Main.Models.Ram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RamCategoryId");

                    b.Property<string>("description");

                    b.Property<string>("img");

                    b.Property<string>("name");

                    b.Property<long>("price");

                    b.HasKey("Id");

                    b.HasIndex("RamCategoryId");

                    b.ToTable("Rams");
                });

            modelBuilder.Entity("ShopPhone.Main.Models.RamCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoryDescription");

                    b.Property<string>("categoryName");

                    b.HasKey("Id");

                    b.ToTable("RamCategories");
                });

            modelBuilder.Entity("ShopPhone.Main.Models.Ssd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SsdCategoryId");

                    b.Property<string>("description");

                    b.Property<string>("img");

                    b.Property<string>("name");

                    b.Property<long>("price");

                    b.HasKey("Id");

                    b.HasIndex("SsdCategoryId");

                    b.ToTable("Ssds");
                });

            modelBuilder.Entity("ShopPhone.Main.Models.SsdCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoryDescription");

                    b.Property<string>("categoryName");

                    b.HasKey("Id");

                    b.ToTable("SsdCategories");
                });

            modelBuilder.Entity("ShopPhone.Main.Models.VideoCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("VideoCardCategoryId");

                    b.Property<string>("description");

                    b.Property<string>("img");

                    b.Property<string>("name");

                    b.Property<long>("price");

                    b.HasKey("Id");

                    b.HasIndex("VideoCardCategoryId");

                    b.ToTable("VideoCards");
                });

            modelBuilder.Entity("ShopPhone.Main.Models.VideoCardCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoryDescription");

                    b.Property<string>("categoryName");

                    b.HasKey("Id");

                    b.ToTable("VideoCardCategories");
                });

            modelBuilder.Entity("ShopPhone.Main.Models.Motherboard", b =>
                {
                    b.HasOne("ShopPhone.Main.Models.MotherboardCategory", "MotherboardCategory")
                        .WithMany("motherboards")
                        .HasForeignKey("MotherboardCategoryId");
                });

            modelBuilder.Entity("ShopPhone.Main.Models.Phone", b =>
                {
                    b.HasOne("ShopPhone.Main.Models.Category", "Category")
                        .WithMany("phones")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("ShopPhone.Main.Models.Procesor", b =>
                {
                    b.HasOne("ShopPhone.Main.Models.ProcesorCategory", "ProcesorCategory")
                        .WithMany("procesors")
                        .HasForeignKey("ProcesorCategoryId");
                });

            modelBuilder.Entity("ShopPhone.Main.Models.Ram", b =>
                {
                    b.HasOne("ShopPhone.Main.Models.RamCategory", "RamCategory")
                        .WithMany("rams")
                        .HasForeignKey("RamCategoryId");
                });

            modelBuilder.Entity("ShopPhone.Main.Models.Ssd", b =>
                {
                    b.HasOne("ShopPhone.Main.Models.SsdCategory", "SsdCategory")
                        .WithMany("ssds")
                        .HasForeignKey("SsdCategoryId");
                });

            modelBuilder.Entity("ShopPhone.Main.Models.VideoCard", b =>
                {
                    b.HasOne("ShopPhone.Main.Models.VideoCardCategory", "VideoCardCategory")
                        .WithMany("videoCards")
                        .HasForeignKey("VideoCardCategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
